[tool.poetry]
name = "ml-from-scratch"
version = "0.1.0"
description = ""
authors = ["MarioDEFRANCE <74489838+mdefrance@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">3.10, <=3.13"
numpy = "^2.2.3"
ipykernel = "^6.29.5"
pytest = "^8.3.4"
black = "^25.1.0"
flake8 = "^7.1.2"
isort = "^6.0.1"
flake8-pyproject = "^1.2.3"
pylint = "^3.3.4"
scikit-learn = "^1.6.1"
torch = {version = "^2.6.0", source = "pytorch-gpu"}
torchvision = {version = "^0.21.0", source = "pytorch-gpu"}
torchaudio = {version = "^2.6.0", source = "pytorch-gpu"}


[[tool.poetry.source]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "E704"]


[tool.pylint.basic]
good-names = ["X", "y"]

[tool.pylint.messages_control]
disable = ["C0301", "C0103", "E0110", "W0621", "import-error"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "scikit-learn>=1.8.0",
]
